### ISSUE TITLE
Xbox controller shutoff requires game restart

### ISSUE THREAD

**Issue by cbadger360** [ljsimin/MinecraftJoypadSplitscreenMod#28]
I love to play minecraft with my kids using this mod to do splitscreen.  However, one really annoying thing with Xbox 360 controllers in general is that they auto-shutoff after being idle for a certain period of time.  Unfortunately with the joypad mod you cannot simply turn the controller back on and go about your way.  You have to shut down the entire game and restart it before the joypad mod will recognize the controller again.  if there's any way this could be fixed, it would be a tremendous help.  Even if you're required to go back into the controllers settings and reactivate the controller I would be fine with that. Just as long as you don't have to shut down the entire game and restart it.

Great job on this mod in general however.  Thanks!

**Comment by ljsimin** [comment]
I think re-detecting in options might be feasible, depending on what APIs the underlying LWJGL library provides.

**Comment by ahickey** [comment]
I spent a couple days in the past researching this because that's one of my biggest problems with this mod too.  
LWJGL makes a single call to GetCurrentEnvironment in the constructor and stores the results in an array.  It never makes the call again.  GetCurrentEnvironment is the call to Windows to enumerate the connected devices.  
LWJGL doesn't have a built in method for refreshing this array.   All other Java games which use LWJGL for controllers suffer the same problem.
I tried to access the private stored array in LWJGL to periodically refresh it but I kept getting security context violations.  
I also tried using just the JGL that LWJGL wraps but this was not possible because Minecraft loads the LWJGL by default even without the joypad mod.  And because of Java's context security restrictions I was unable to load the JGL in the session our mod is loaded in.  
Perhaps a future version of LWJGL will resolve this issue.

On Apr 24, 2016 12:15 AM, Ljubomir Simin <notifications@github.com> wrote:I think re-detecting in options might be feasible, depending on what APIs the underlying LWJGL library provides.

**Comment by ljsimin** [comment]
@ahickey Can we ship our own version of LWJGL with the mod? One way would be to fork it, make necessary changes, include modified classes within the mod and import them in our code in place of original ones. Might have some issues with 2 libraries trying to access hardware though.

If that worked we should submit the patch upstream.

**Comment by ahickey** [comment]
I suspect the problem will be in using the Java Games Library.  Our custom LWJGL would need it in addition to the original LWJGL that the base Minecraft game loads at startup.  There is a problem when different class loaders try to load the same library that I do not know how to resolve.
On Apr 24, 2016 12:27 PM, Ljubomir Simin <notifications@github.com> wrote:@ahickey Can we ship our own version of LWJGL with the mod? One way would be to fork it, make necessary changes, include modified classes within the mod and import them in our code in place of original ones. Might have some issues with 2 libraries trying to access hardware though.

If that worked we should submit the patch upstream.

**Comment by cbadger360** [comment]
Ah, I didn't realize Minecraft itself was built on LWJGL, and that the joypad mod shared the same library instances.  Seems like this problem will be a lot harder to solve as a result.  Hopefully LWJGL will provide some way to address this in the future, and Minecraft will adopt that new version.  Either way, I appreciate the responses.

**Comment by ljsimin** [comment]
@ahickey Then an alternative would be to implement our own controller input routines on top of Jinput or something similar.

**Comment by ahickey** [comment]
Fixed in latest 1.11 check in

**Comment by cbadger360** [comment]
Awesome, if this works you're a hero!  This makes the joypad mod far more useful when you have a bunch of kids huddled around a split-screen, who tend to walk away and come back to a powered off controller.  Thanks again for putting time and effort into this.

**Comment by el-brio** [comment]
I still have this issue using the latest version (I think) on 1.12.2.  the version I have is 1.12.2 - 1.11.  Can someone help me please?
